updated scripts to have their own check for if things are installed, and removed some stuff from the README since the scripts handle some of it now

diff --git a/bin/update_mirrors b/bin/update_mirrors
--- a/bin/update_mirrors
+++ b/bin/update_mirrors
@@ -1,3 +1,10 @@
 #!/usr/bin/env sh
+if ! is_command reflector; then
+    >&2 echo "This script is made for EndeavourOS and reflector can't be found"
+    exit 1
+elif ! is_command eos-rankmirrors; then
+    >&2 echo "This script is made for EndeavourOS and eos-rankmirrors can't be found"
+    exit 2
+fi
 sudo reflector --verbose --protocol https --latest 50 --sort rate --save /etc/pacman.d/mirrorlist
 eos-rankmirrors
